# Generated by Django 3.2.11 on 2022-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('theBorrower', models.TextField()),
                ('nominal', models.TextField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('imagePaths', models.ImageField(default='test.jpg', upload_to='images')),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('editedTime', models.DateTimeField(auto_now=True)),
                ('createdBy', models.TextField()),
                ('lastEditedBy', models.TextField(default='')),
                ('lastSync', models.CharField(blank=True, max_length=128, null=True)),
                ('isDeleted', models.TextField(default='false')),
            ],
            options={
                'ordering': ['editedTime'],
            },
        ),
    ]
