# Generated by Django 3.2.11 on 2022-02-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('theBorrower', models.TextField()),
                ('nominal', models.TextField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('editedTime', models.DateTimeField(auto_now=True)),
                ('createdBy', models.TextField()),
                ('lastEditedBy', models.TextField()),
            ],
            options={
                'ordering': ['editedTime'],
            },
        ),
    ]
