# Generated by Django 3.2.11 on 2022-02-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='imagePaths',
            field=models.ImageField(default='test.jpg', upload_to='image'),
        ),
    ]
