# Generated by Django 3.2.11 on 2022-03-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='imagePaths',
            field=models.ImageField(blank=True, default='test.jpg', null=True, upload_to='images'),
        ),
    ]
