# Generated by Django 3.2.11 on 2022-03-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_imagepaths'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='idSupir',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='note',
            name='jumlahRit',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='note',
            name='platNomor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
