# Generated by Django 3.2.11 on 2022-02-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_imagepaths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lastEditedBy',
            field=models.TextField(default=''),
        ),
    ]
