# Generated by Django 3.2.11 on 2022-03-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_note_lasteditedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='lastSync',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='imagePaths',
            field=models.ImageField(default='test.jpg', upload_to='images'),
        ),
    ]
