# Generated by Django 3.2.11 on 2022-03-04 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220304_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lastSync',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
