# Generated by Django 3.2.11 on 2022-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220321_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasupir',
            name='idSup',
            field=models.TextField(verbose_name='ID SUPIR'),
        ),
        migrations.AlterField(
            model_name='datasupir',
            name='jenis',
            field=models.TextField(verbose_name='JENIS'),
        ),
        migrations.AlterField(
            model_name='datasupir',
            name='namaSupir',
            field=models.TextField(verbose_name='NAMA SUPIR'),
        ),
        migrations.AlterField(
            model_name='datasupir',
            name='noPol',
            field=models.TextField(verbose_name='PLAT NOMOR'),
        ),
        migrations.AlterField(
            model_name='datasupir',
            name='passSupir',
            field=models.TextField(verbose_name='PASSWORD SUPIR'),
        ),
        migrations.AlterField(
            model_name='note',
            name='createdBy',
            field=models.TextField(verbose_name='DIBUAT OLEH'),
        ),
        migrations.AlterField(
            model_name='note',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='TANGGAL DIBUAT'),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='DESKRIPSI'),
        ),
        migrations.AlterField(
            model_name='note',
            name='editedTime',
            field=models.DateTimeField(auto_now=True, verbose_name='TANGGAL DIUBAH'),
        ),
        migrations.AlterField(
            model_name='note',
            name='idSupir',
            field=models.CharField(default='', max_length=100, verbose_name='ID SUPIR'),
        ),
        migrations.AlterField(
            model_name='note',
            name='imagePaths',
            field=models.ImageField(blank=True, default='test.jpg', null=True, upload_to='images', verbose_name='PHOTO'),
        ),
        migrations.AlterField(
            model_name='note',
            name='isDeleted',
            field=models.TextField(default='false', verbose_name='STATUS HAPUS'),
        ),
        migrations.AlterField(
            model_name='note',
            name='jumlahRit',
            field=models.CharField(default='', max_length=100, verbose_name='JUMLAH RIT'),
        ),
        migrations.AlterField(
            model_name='note',
            name='lastEditedBy',
            field=models.TextField(default='', verbose_name='TERAKHIR DIEDIT OLEH'),
        ),
        migrations.AlterField(
            model_name='note',
            name='lastSync',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='TERAKHIR DISYNC'),
        ),
        migrations.AlterField(
            model_name='note',
            name='nominal',
            field=models.TextField(verbose_name='NOMINAL'),
        ),
        migrations.AlterField(
            model_name='note',
            name='platNomor',
            field=models.CharField(default='', max_length=100, verbose_name='PLAT NOMOR'),
        ),
        migrations.AlterField(
            model_name='note',
            name='theBorrower',
            field=models.TextField(verbose_name='NAMA SUPIR'),
        ),
    ]
