# Generated by Django 3.2.11 on 2022-03-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_note_lastsync'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='isDeletd',
            field=models.BooleanField(default=False),
        ),
    ]
