# Generated by Django 3.2.11 on 2022-03-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_note_isdeletd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='isDeletd',
            field=models.TextField(default='false'),
        ),
    ]
