# Generated by Django 3.2.11 on 2022-03-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_note_isdeletd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='isDeletd',
            new_name='isDeleted',
        ),
    ]
